### ISSUE TITLE
escape brackets (& parens?)

### ISSUE THREAD

**Issue by fmof** [joshua-decoder/joshua#106]
Joshua doesn't properly escape brackets (and possibly parens). I ran into this while trying to true-case some English text. This was on test4. Running with v5.0-rc3, the <tt>JOSHUA</tt> environment variable set:

<pre>
$ ./run-joshua.sh -server-port 5995 -threads 1
#assume $FILE is set to a local file
#grab the first "real" line of it
$ head -n3 $FILE | tail -n1 | nc test4 5995
Translating sentence #0 [thread 9]: 'SAN SALVADOR, 3 JAN 90 -- [REPORT] [ARMED FORCES PRESS COMMITTEE, COPREFA] [TEXT] THE ARCE BATTALION COMMAND HAS REPORTED THAT ABOUT 50 PEASANTS OF VARIOUS AGES HAVE BEEN KIDNAPPED BY TERRORISTS OF THE FARABUNDO MARTI NATIONAL LIBERATION FRONT [FMLN] IN SAN MIGUEL DEPARTMENT. ACCORDING TO THAT GARRISON, THE MASS KIDNAPPING TOOK PLACE ON 30 DECEMBER IN SAN LUIS DE LA REINA. THE SOURCE ADDED THAT THE TERRORISTS FORCED THE INDIVIDUALS, WHO WERE TAKEN TO AN UNKNOWN LOCATION, OUT OF THEIR RESIDENCES, PRESUMABLY TO INCORPORATE THEM AGAINST THEIR WILL INTO CLANDESTINE GROUPS.'
Exception in thread "Thread-4" java.lang.NullPointerException
        at joshua.decoder.ff.state_maintenance.NgramStateComputer.computeState(NgramStateComputer.java:56)
        at joshua.decoder.ff.state_maintenance.NgramStateComputer.computeState(NgramStateComputer.java:13)
        at joshua.decoder.chart_parser.ComputeNodeResult.<init>(ComputeNodeResult.java:71)
        at joshua.decoder.chart_parser.Chart.completeSpan(Chart.java:330)
        at joshua.decoder.chart_parser.Chart.expand(Chart.java:486)
        at joshua.decoder.DecoderThread.translate(DecoderThread.java:107)
        at joshua.decoder.Decoder$DecoderThreadRunner.run(Decoder.java:248)
</pre>

**Comment by mjpost** [comment]
This should be fixed as of commit dee842dc8617ada9a7479311fb716d24120bfefc
