### ISSUE TITLE
Decoder fails if"feature-function = Distortion" option is used

### ISSUE THREAD

**Issue by keisks** [joshua-decoder/joshua#187]
The following error occurred when Distortion function (in src/joshua/decoder/ff/phrase/Distortion.java) is used.

    java.lang.NullPointerException
        at joshua.decoder.ff.phrase.Distortion.compute(Distortion.java:28)
        at joshua.decoder.chart_parser.ComputeNodeResult.<init>(ComputeNodeResult.java:88)
        at joshua.decoder.chart_parser.Chart.completeSpan(Chart.java:238)
        at joshua.decoder.chart_parser.Chart.expand(Chart.java:580)
        at joshua.decoder.DecoderThread.translate(DecoderThread.java:119)
        at joshua.decoder.Decoder$DecoderThreadRunner.run(Decoder.java:224)

**Comment by mjpost** [comment]
Are you doing syntax-based decoding? I suspect you are, so this phrase-exclusive feature is causing a problem that should be checked for.
