### ISSUE TITLE
Unable to load a gzipped binarized BerkeleyLM

### ISSUE THREAD

**Issue by fhieber** [joshua-decoder/joshua#194]
It seems like there is a bug in determining whether a BerkeleyLM is in binary format (result of 'edu.berkeley.nlp.lm.io.MakeLmBinaryFromArpa' with output file specified as lm.binary.gz).

If joshua is supplied with a config containing
> feature-function = LanguageModel -lm_type berkeleylm -lm_order 3 -lm_file lm.binary.gz

it attempts to use the ARPA loader:
> Loading Berkeley LM from ARPA file lm.binary.gz
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at joshua.decoder.Decoder.initializeFeatureFunctions(Decoder.java:657)
	at joshua.decoder.Decoder.initialize(Decoder.java:466)
	at joshua.decoder.Decoder.<init>(Decoder.java:98)
	at joshua.decoder.JoshuaDecoder.main(JoshuaDecoder.java:45)
Caused by: java.lang.RuntimeException: Something wrong with I/O.
	at edu.berkeley.nlp.lm.io.ArpaLmReader.parseHeader(ArpaLmReader.java:114)
	at edu.berkeley.nlp.lm.io.ArpaLmReader.parse(ArpaLmReader.java:76)
	at edu.berkeley.nlp.lm.io.ArpaLmReader.parse(ArpaLmReader.java:18)
	at edu.berkeley.nlp.lm.io.LmReaders.firstPassCommon(LmReaders.java:549)
	at edu.berkeley.nlp.lm.io.LmReaders.firstPassArpa(LmReaders.java:526)
	at edu.berkeley.nlp.lm.io.LmReaders.readArrayEncodedLmFromArpa(LmReaders.java:171)
	at edu.berkeley.nlp.lm.io.LmReaders.readArrayEncodedLmFromArpa(LmReaders.java:151)
	at joshua.decoder.ff.lm.berkeley_lm.LMGrammarBerkeley.<init>(LMGrammarBerkeley.java:84)
	at joshua.decoder.ff.lm.LanguageModelFF.initializeLM(LanguageModelFF.java:150)
	at joshua.decoder.ff.lm.LanguageModelFF.<init>(LanguageModelFF.java:135)

If the binary lm is not gzipped, i.e. lm.binary, loading works fine:
> ...
> Loading Berkeley LM from binary lm.binary
> ...

I guess that
> /JoshuaMachineTranslationEngine/src/joshua/decoder/ff/lm/berkeley_lm/LMGrammarBerkeley.java:63

that is
> new ObjectInputStream(new BufferedInputStream(new FileInputStream(new File(lm_file))));

does not work as expected.

Is there a workaround for this?
Thank you!

**Comment by mjpost** [comment]
This is actually the intended functionality, the assumption being that there isn't much purpose in compressing the binarized format. Why are you compressing the binarized format? What compression ratio are you getting? If you're getting a good compression ratio then we could perhaps reconsider this logic.

**Comment by fhieber** [comment]
Oh ok. I was assuming support of gzipped binaries because the BerkeleyLM code simply does it when the binary output filename ends with '.gz'.
And it also seems that compressing a binary lm does save some disk space:
> 13G text
13G text.arpa
4.3G text.binary
3.0G text.binary.gz

where text.binary is the unzipped version of text.binary.gz.

**Comment by mjpost** [comment]
All right, it seems reasonable to support this. If you want to take a stab at it, it should be pretty easy — just try to open the compiled format, and if that fails, try it as ARPA. I will keep this on my list of things to do but may not get to it for a while.

**Comment by fhieber** [comment]
Cool, thanks! I will give it a try tomorrow and send you a pull request once done.

**Comment by mjpost** [comment]
This was fixed with when 94c01a1028919be297ebaf797d456b8b3cf3980d was merged in.
