### ISSUE TITLE
Bug in params.txt reading in PRO

### ISSUE THREAD

**Issue by fhieber** [joshua-decoder/joshua#211]
There seems to be a bug in reading parameter specification in params.txt when running PRO:
Exception in thread "main" java.lang.NumberFormatException: For input string: "tm_pt_1"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at joshua.pro.PROCore.processParamFile(PROCore.java:1670)
	at joshua.pro.PROCore.initialize(PROCore.java:328)
	at joshua.pro.PROCore.<init>(PROCore.java:246)
	at joshua.pro.PRO.main(PRO.java:27)

AdaGrad seems to skip the MERT-related +Inf/-Inf columns correctly in the else block: https://github.com/joshua-decoder/joshua/blob/master/src/joshua/adagrad/AdaGradCore.java#L1695.

PRO however has 'double skips':
https://github.com/joshua-decoder/joshua/blob/master/src/joshua/pro/PROCore.java#L1652 (and line 1662).

**Comment by mjpost** [comment]
Are you using the development version of Joshua, or the 6.0.4 point release?

**Comment by fhieber** [comment]
most recent commit (1886c08dd7cc480344796cd214f521eb5ecf7b24)

**Comment by mjpost** [comment]
Thanks!
