### ISSUE TITLE
ArrayIndexOutOfBoundsException when passing arguments to JoshuaDecoder.main

### ISSUE THREAD

**Issue by lewismc** [joshua-decoder/joshua#221]
```
lmcgibbn@LMC-032857 /usr/local/joshua(master) $ java -jar class/joshua.jar -version
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
	at joshua.decoder.ArgsParser.<init>(ArgsParser.java:43)
	at joshua.decoder.JoshuaDecoder.main(JoshuaDecoder.java:30)
lmcgibbn@LMC-032857 /usr/local/joshua(master) $ java -jar class/joshua.jar -version -v
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
	at joshua.decoder.ArgsParser.<init>(ArgsParser.java:43)
	at joshua.decoder.JoshuaDecoder.main(JoshuaDecoder.java:30)
```

**Comment by mjpost** [comment]
Hmm. I suspect this is because, although we build the jar, we don't use it at all. Why are you trying to use the jar, instead of, e.g., $JOSHUA/bin/joshua-decoder?

**Comment by lewismc** [comment]
I was inside of Eclipse

**Comment by lewismc** [comment]
Was trying to debug something inside of Eclipse on this occasion.

**Comment by mjpost** [comment]
All right. I haven't used this at all, so I'm not sure what the problem is. In general, I don't use the jar, because it slows down debugging (you have to rebuild the jar after every change)
