### ISSUE TITLE
Unbound variable in joshua-decoder script

### ISSUE THREAD

**Issue by lewismc** [joshua-decoder/joshua#234]
This was reported by the Homebrew Jenkins CI build server
```
Error Message

failed: brew test --verbose joshua

Stacktrace

        Testing joshua
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20151106-70367-hbqww0.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/joshua.rb --verbose
==> /usr/local/Cellar/joshua/6.0.5/bin/joshua-decoder -version
/usr/local/Cellar/joshua/6.0.5/bin/joshua-decoder: line 27: JOSHUA: unbound variable
Error: joshua: failed
Failed executing: /usr/local/Cellar/joshua/6.0.5/bin/joshua-decoder -version
/usr/local/Library/Homebrew/formula.rb:1431:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1368:in `open'
/usr/local/Library/Homebrew/formula.rb:1368:in `system'
/usr/local/Library/Formula/joshua.rb:59:in `block in <class:Joshua>'
/usr/local/Library/Homebrew/formula.rb:1277:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1273:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'

      
```

**Comment by mjpost** [comment]
`$JOSHUA/bin/joshua-decoder` requires that `$JOSHUA` be defined. I will push up a change that instead sets this from within the script based on the path of the called file.

**Comment by lewismc** [comment]
That would be nice. Please feel free to rename this issue @mjpost

**Comment by mjpost** [comment]
Should be fixed now, in the dist. tarballs as well.

**Comment by lewismc** [comment]
@mjpost 

>  in the dist. tarballs as well.

Do you mean that this is present in the new Joshua 6.0.5? Did you respin the release?

**Comment by mjpost** [comment]
Yes, this is now fixed in the downloadable tarballs. 

matt (from my phone)
